title: BlueMap
description: >-
  BlueMap is a Minecraft mapping tool that creates 3D models of your Minecraft worlds and displays them in a web viewer.
theme: just-the-docs
color_scheme: dark


baseurl: ""
url: ""

aux_links:
  "BlueMap on GitHub": "https://github.com/BlueMap-Minecraft/BlueMap"

gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/BlueMap-Minecraft/bluemap-minecraft.github.io"
gh_edit_branch: "master"
gh_edit_view_mode: "edit"

exclude:
  - .idea/

sass:
  quiet_deps: true # https://github.com/just-the-docs/just-the-docs/issues/1541
  silence_deprecations: ['import'] # https://github.com/just-the-docs/just-the-docs/issues/1607

gems:
  - jekyll-relative-links